basePath = "Interface\\AddOns\\TwitchEmotes_Hardcore\\emotes\\";
TwitchEmotes_animation_metadata[basePath .. "KEKWSPIN.tga"] = {["nFrames"] = 20, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "spilledGlue.tga"] = {["nFrames"] = 13, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "KEKDance.tga"] = {["nFrames"] = 24, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "KEKFlute.tga"] = {["nFrames"] = 64, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "jokerBonk.tga"] = {["nFrames"] = 14, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "DIESOFCRINGE.tga"] = {["nFrames"] = 73, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "KEKIUM.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "SALAMI.tga"] = {["nFrames"] = 4, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 128, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "PUMP.tga"] = {["nFrames"] = 9, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "GIGABULL.tga"] = {["nFrames"] = 144, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "ankhaBounce.tga"] = {["nFrames"] = 13, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "ankhaPeek.tga"] = {["nFrames"] = 171, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "GIGAANKHA.tga"] = {["nFrames"] = 194, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "IKENT.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "ok.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "KEKBye.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 10}
TwitchEmotes_animation_metadata[basePath .. "DJKek.tga"] = {["nFrames"] = 226, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "CANTSTOPKEK.tga"] = {["nFrames"] = 17, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "ThatsEnough.tga"] = {["nFrames"] = 82, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "DUGA.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "peepoDig.tga"] = {["nFrames"] = 89, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Tssk.tga"] = {["nFrames"] = 24, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "AlienPls3.tga"] = {["nFrames"] = 73, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Ridicule.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "monkePls.tga"] = {["nFrames"] = 87, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "DougDimmadomeOwnerOfTheDimmsdaleDimmadomeLookingOutHisDimmsdaleDimmadome.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "AGGREND.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Listening.tga"] = {["nFrames"] = 162, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "OMEGAKEK.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "KEKInsane.tga"] = {["nFrames"] = 15, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "mhm.tga"] = {["nFrames"] = 9, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 5}
TwitchEmotes_animation_metadata[basePath .. "ReallyNice.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "HUHA.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "NewSkirt.tga"] = {["nFrames"] = 45, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "NightRoutine.tga"] = {["nFrames"] = 147, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "KEKDoctor.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "CAUGHT.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "COT.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "SummoningTheDemons.tga"] = {["nFrames"] = 190, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "BASED.tga"] = {["nFrames"] = 82, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "KEK4K.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "LICKA.tga"] = {["nFrames"] = 58, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Pfft.tga"] = {["nFrames"] = 41, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "kekYO.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "xdd666.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "jokerdNoBita.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "KEKBrows.tga"] = {["nFrames"] = 10, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "CHADDING.tga"] = {["nFrames"] = 76, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "KEKBoom.tga"] = {["nFrames"] = 96, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "sus.tga"] = {["nFrames"] = 163, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "CameraMan.tga"] = {["nFrames"] = 241, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "NOOO.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "NAUR.tga"] = {["nFrames"] = 4, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 128, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "YAP.tga"] = {["nFrames"] = 117, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "AstolfoBounce.tga"] = {["nFrames"] = 12, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "AstolfoSway.tga"] = {["nFrames"] = 45, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "SoCute.tga"] = {["nFrames"] = 12, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "TrashStomp.tga"] = {["nFrames"] = 20, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 10}
TwitchEmotes_animation_metadata[basePath .. "FemboyPolish.tga"] = {["nFrames"] = 100, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "FemboyHips.tga"] = {["nFrames"] = 66, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "astolfoBooty.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "ShowSkin.tga"] = {["nFrames"] = 250, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 45}
TwitchEmotes_animation_metadata[basePath .. "Femboy.tga"] = {["nFrames"] = 138, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 45}
TwitchEmotes_animation_metadata[basePath .. "AstolfoFeet.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Booty.tga"] = {["nFrames"] = 118, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "scrajj.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 5}
TwitchEmotes_animation_metadata[basePath .. "KEEEEEEEK.tga"] = {["nFrames"] = 50, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "WOT.tga"] = {["nFrames"] = 72, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "BoysBeingBoys.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "femboyKiss.tga"] = {["nFrames"] = 101, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "sitHere.tga"] = {["nFrames"] = 234, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "cringe.tga"] = {["nFrames"] = 147, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "CocaCola.tga"] = {["nFrames"] = 181, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "UltraMad.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "MorningRoutine.tga"] = {["nFrames"] = 152, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Blush.tga"] = {["nFrames"] = 20, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 10}
TwitchEmotes_animation_metadata[basePath .. "SillyBoykisser.tga"] = {["nFrames"] = 8, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 10}
TwitchEmotes_animation_metadata[basePath .. "BoyChatter.tga"] = {["nFrames"] = 16, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 10}
TwitchEmotes_animation_metadata[basePath .. "Mayhaps.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "AINTNAURWAY.tga"] = {["nFrames"] = 69, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "AINTNOWAY.tga"] = {["nFrames"] = 69, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 12}
TwitchEmotes_animation_metadata[basePath .. "FingerGuns.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Erm.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "jokerParty.tga"] = {["nFrames"] = 83, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "jokerFight.tga"] = {["nFrames"] = 86, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "ReallyNah.tga"] = {["nFrames"] = 26, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 20}
TwitchEmotes_animation_metadata[basePath .. "docNotL.tga"] = {["nFrames"] = 60, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 20}
TwitchEmotes_animation_metadata[basePath .. "HesRight.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "CatboyRawr.tga"] = {["nFrames"] = 27, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "owo.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "ohStop.tga"] = {["nFrames"] = 66, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "BEGGING.tga"] = {["nFrames"] = 251, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "docL.tga"] = {["nFrames"] = 46, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 15}
TwitchEmotes_animation_metadata[basePath .. "KEKLeave.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "KEKInteresting.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "KEK7.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "forsenLaughingAtYou.tga"] = {["nFrames"] = 72, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Femboys.tga"] = {["nFrames"] = 120, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "YEAHBUTITSLIKEATHIRDPARTYTHING.tga"] = {["nFrames"] = 102, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "Giggleg.tga"] = {["nFrames"] = 2, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 64, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Awkward.tga"] = {["nFrames"] = 81, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "uuh.tga"] = {["nFrames"] = 41, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "CaughtIn4K.tga"] = {["nFrames"] = 33, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Milk.tga"] = {["nFrames"] = 21, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "ono.tga"] = {["nFrames"] = 48, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "docYELL.tga"] = {["nFrames"] = 38, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "fishnet.tga"] = {["nFrames"] = 157, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "buh.tga"] = {["nFrames"] = 117, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "duh.tga"] = {["nFrames"] = 40, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "huh.tga"] = {["nFrames"] = 93, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "muh.tga"] = {["nFrames"] = 43, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "juh.tga"] = {["nFrames"] = 171, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "puh.tga"] = {["nFrames"] = 32, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "fuh.tga"] = {["nFrames"] = 199, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "ImSorrySister.tga"] = {["nFrames"] = 24, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "HeyCutie.tga"] = {["nFrames"] = 103, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "AMBATUKAM.tga"] = {["nFrames"] = 92, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "femboyPls.tga"] = {["nFrames"] = 37, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 25}
TwitchEmotes_animation_metadata[basePath .. "tasty.tga"] = {["nFrames"] = 44, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "CATBOOB.tga"] = {["nFrames"] = 118, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "fingerjob.tga"] = {["nFrames"] = 57, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "punish.tga"] = {["nFrames"] = 135, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "punish.tga"] = {["nFrames"] = 68, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "fingerjob.tga"] = {["nFrames"] = 57, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "pole.tga"] = {["nFrames"] = 32, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 20}
TwitchEmotes_animation_metadata[basePath .. "LickYou.tga"] = {["nFrames"] = 44, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "forsenCoomer.tga"] = {["nFrames"] = 97, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "IFISPEAKBIGTROUBLE.tga"] = {["nFrames"] = 101, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "fingerjob.tga"] = {["nFrames"] = 57, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "fingerjob.tga"] = {["nFrames"] = 57, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Arfus.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Dentge.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Fishinge.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "gothSit.tga"] = {["nFrames"] = 41, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "pokiKiss.tga"] = {["nFrames"] = 93, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Sprite.tga"] = {["nFrames"] = 157, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "FeelsLewdMan.tga"] = {["nFrames"] = 104, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 25}
TwitchEmotes_animation_metadata[basePath .. "POGGIES.tga"] = {["nFrames"] = 126, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "jokerdVibe.tga"] = {["nFrames"] = 67, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 25}
TwitchEmotes_animation_metadata[basePath .. "jokerdKiss.tga"] = {["nFrames"] = 67, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 25}
TwitchEmotes_animation_metadata[basePath .. "Homies.tga"] = {["nFrames"] = 59, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "YuuBooty.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "THOSE.tga"] = {["nFrames"] = 13, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Hypnosis.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "tailwag.tga"] = {["nFrames"] = 15, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "strapped.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "aaaaaaaaaaaaaaaaaaaa.tga"] = {["nFrames"] = 3, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 128, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "aaaa.tga"] = {["nFrames"] = 4, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 128, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "MUGA.tga"] = {["nFrames"] = 112, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "WDYM.tga"] = {["nFrames"] = 55, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "SCHIZO.tga"] = {["nFrames"] = 48, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "docPls.tga"] = {["nFrames"] = 128, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "femboyFeet.tga"] = {["nFrames"] = 65, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "Pointless.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "HarryKane.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "hawktuah.tga"] = {["nFrames"] = 74, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "GULP.tga"] = {["nFrames"] = 47, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 2048, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "OOOOO.tga"] = {["nFrames"] = 90, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "SAVEME.tga"] = {["nFrames"] = 1, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 32, ["framerate"] = 18}TwitchEmotes_animation_metadata[basePath .. "glorpShakey.tga"] = {["nFrames"] = 24, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "glorprave.tga"] = {["nFrames"] = 24, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "euh.tga"] = {["nFrames"] = 98, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "zyzzDance.tga"] = {["nFrames"] = 96, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 4096, ["framerate"] = 30}
TwitchEmotes_animation_metadata[basePath .. "catPls.tga"] = {["nFrames"] = 30, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 1024, ["framerate"] = 18}
TwitchEmotes_animation_metadata[basePath .. "pokePls.tga"] = {["nFrames"] = 144, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 8192, ["framerate"] = 18}
